licenses(["notice"])  # Apache 2

package(default_visibility = ["//visibility:public"])

alias (
    name = "crypto_utility_headers_lib",
    actual = "@envoy_openssl//source/common/crypto:utility_lib",
)

alias (
    name = "crypto_utility_lib",
    actual = "@envoy_openssl//source/extensions/common/crypto:utility_lib",
)

alias (
    name = "tls_inspector_lib",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:tls_inspector_lib",
)

alias (
    name = "tls_inspector_config",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:config",
)

alias (
    name = "tls_inspector_test_utility_lib",
    actual = "@envoy_openssl//test/extensions/filters/listener/tls_inspector:tls_utility_lib",
)

alias (
    name = "openssl_impl_lib",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:openssl_impl_lib",
)

alias (
    name = "tls_config",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:config",
)

alias (
    name = "tls_context_config_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:context_config_lib",
)

alias (
    name = "tls_context_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:context_lib",
)

alias (
    name = "tls_utility_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:utility_lib",
)

alias (
    name = "tls_ssl_socket_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:ssl_socket_lib",
)

alias (
    name = "tls_test_data_certs",
    actual = "@envoy_openssl//test/extensions/transport_sockets/tls/test_data:certs",
)

alias (
    name = "tls_test_data_cert_infos",
    actual = "@envoy_openssl//test/extensions/transport_sockets/tls/test_data:cert_infos",
)

alias (
    name = "tls_ssl_test_utils",
    actual = "@envoy_openssl//test/extensions/transport_sockets/tls:ssl_test_utils",
)

alias (
    name = "lua_filter_lib",
    actual = "@envoy_openssl//source/extensions/filters/http/lua:lua_filter_lib",
)

alias (
    name = "lua_wrappers_lib",
    actual = "@envoy_openssl//source/extensions/filters/http/lua:wrappers_lib",
)

alias (
    name = "lua_config",
    actual = "@envoy_openssl//source/extensions/filters/http/lua:config",
)
