licenses(["notice"])  # Apache 2

package(default_visibility = ["//visibility:public"])

alias (
    name = "crypto_utility_lib",
    actual = "@envoy_openssl//source/extensions/common/crypto:utility_lib",
)

alias (
    name = "tls_inspector_lib",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:tls_inspector_lib",
)

alias (
    name = "tls_inspector_config",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:config",
)

alias (
    name = "openssl_impl_lib",
    actual = "@envoy_openssl//source/extensions/filters/listener/tls_inspector:openssl_impl_lib",
)

alias (
    name = "tls_config",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:config",
)

alias (
    name = "tls_context_config_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:context_config_lib",
)

alias (
    name = "tls_context_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:context_lib",
)

alias (
    name = "tls_utility_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:utility_lib",
)

alias (
    name = "tls_ssl_socket_lib",
    actual = "@envoy_openssl//source/extensions/transport_sockets/tls:ssl_socket_lib",
)

alias (
    name = "tls_test_data_certs",
    actual = "@envoy_openssl//test/extensions/transport_sockets/tls/test_data:certs",
)

